name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Install Mocha
        run: npm install --save-dev mocha --force

      - name: Configure environment
        run: |
          export PATH=$(npm bin):$PATH
          echo "Updated PATH: $PATH"

      - name: Verify Mocha installation
        run: npx mocha --version

      - name: Debug environment
        run: |
          ls -la node_modules/.bin/
          node --version
          npm --version
          which mocha

      - name: Run test_ecommerce.mjs
        run: npx mocha test_ecommerce.mjs --no-warnings
        continue-on-error: true

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Build frontend
        run: |
          cd frontend
          npm install || echo "No package.json dependencies to install"
          npm run build || echo "No build script defined"

  open-pull-request:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Open pull request (placeholder)
        run: echo "This is a placeholder for opening a pull request. Add your logic here if needed."